ARCHS = armv7 arm64

BUNDLE_NAME = BadgeCleaner
BadgeCleaner_FILES = Switch.x
BadgeCleaner_FRAMEWORKS = UIKit
BadgeCleaner_LIBRARIES = flipswitch
BadgeCleaner_INSTALL_PATH = /Library/Switches

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk